config/routes.rb
Rails.application.routes.draw do
  devise_for :users #, sign_out_via: [:get, :delete]
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :new, :create, :destroy] do
          resources :comments, except: [edit, update]
        end
      end
    end
  end
  # Defines the root path route ("/")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can %i[read create], Post
    can %i[read create], Comment
    can [:create], Like
    can %i[update destroy], Post, author_id: user.id
    can %i[update destroy], Comment, author_id: user.id

    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_create :update_comments_counter

  validates :text, presence: true

  def update_comments_counter
    post.update(comments_counter: post.comments.size)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # update post_counter after create
  after_create :update_post_counter

  def update_post_counter
    author.update(posts_counter: author.posts.size)
  end

  def recent_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @comments = Comment.where(post_id: params[:post_id])
    if @comments.empty?
      render json: { error: 'No comments found' }
    else
      render json: @comments
    end
  end

  def new
    render json: Comment.new
  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      render json: comment
    else
      render json: comment.errors
    end
  end

  def comment_params
    params.require(:comment).permit(:text, :author_id, :post_id)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    posts = Post.where(author_id: current_user.id)
    if posts.empty?
      render json: { error: 'No posts found' }
    else
      render json: posts
    end
  end

  def show
    specific_post = Post.find(params[:id])
    if specific_post.nil?
      json_response({ error: 'No post found' }, :not_found)
    else
      render json: specific_post
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    render json: User.all, status: :ok
  end

  def show
    render json: User.find(params[:id]), status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  # Determine where to redirect user after successful login.
  def after_sign_in_path_for(_resource)
    users_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      @comment.update_comments_counter
      flash[:success] = 'Comment was successfully deleted.'

    else
      flash[:error] = 'Comment was not deleted.'
    end
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:success] = 'Comment added successfully'
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      flash.now[:error] = 'Comment not added'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author_id = current_user.id
    @like.post_id = params[:post_id]
    if @like.save
      flash[:notice] = 'Like added successfully'
    else
      flash.now[:error] = 'Like not added'
    end
    redirect_to "/users/#{current_user.id}/posts"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: [:comments]).find(params[:user_id])
    @all_posts = @user.posts.paginate(page: params[:page], per_page: 3)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      @post.update_post_counter
      flash[:success] = 'Post was successfully deleted.'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'Post was not deleted.'
      render :show
    end
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post was successfully created.'
      redirect_to user_post_path(current_user, @post)
    else
      flash.now[:error] = 'Post was not created.'
      render :new
    end
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/post_helper.rb
module Api::V1::PostHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="main">
  <h1>Add a comment</h1>
  <%= form_with model: @comment, url: user_post_comments_path, method: :post, locals: true, scope: :comment do |f| %>
    <div>
      <%= f.text_area :text, placeholder: "Enter your comment", size: "50x3" %>
    </div>
    <%= f.submit 'Add Comment', class: 'btn btn-outline-secondary' %>
  <% end %>
</section>

app/views/posts/index.html.erb
<article class='main container'>
  <h1> All posts </h1>
  <%= render 'shared/user', user: @user %>

  <article class="posts__comments">
    <% @all_posts.each do |post| %>
      <%= link_to "./posts/#{post.id}" do %>
        <article class="posts__container">
          <h3><%= post.title %></h3>
          <p><%= post.text.truncate_words(15, omission: '...(continued)') %></p>
          <div class="comments__likes__count">
            <span><em><b>Comments: <%= post.comments_counter %></em></b></span>
            <span><em><b>Likes: <%= post.likes_counter %></em></b></span>
          </div>
          <div class="delete__post">
            <% if can? :delete, post %>
            <%= button_to "Delete Post", user_post_path(@user.id, post.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
        </article>
      <% end %>
      <% if post.comments.size > 0 %>
        <ul class="comments__container">
          <% post.recent_comments.each do |comment| %>
            <li>
              <span><em><b><%= comment.author.name %>: </b></em></span>
              <span><%= comment.text %></span>
            </li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </article>
  <div class="pagination d-flex justify-content-center">
    <%= will_paginate @all_posts %>
  </div>
</article>

app/views/posts/new.html.erb
<section class="main container">
  <h1>New Post</h1>
  <%= form_with model: @post, url: user_posts_path, method: :post, locals: true, scope: :new_post do |f| %>
    <div class="title">
      <%= f.text_field :title, placeholder: "Post title", class: "my-2", size: "56x3"%>
    </div>
    <div class="text_body">
      <%= f.text_area :text, placeholder: "Type your post here", size: "60x7" %>
    </div>
    <%= f.submit class: 'btn btn-outline-secondary'%>
  <% end %>
</section>

app/views/posts/show.html.erb
<article class="detailed__post__container container">
  <div class="header flex">
    <h2><%= @post.title %> by <%= @user.name %></h2>
    <div class="comments__likes">
      <span><em><b>Comments: <%= @post.comments_counter %></em></b></span>
      <span><em><b>Likes: <%= @post.likes_counter %></em></b></span>
    </div>
  </div>
    <article class="post__content">
      <p><%= @post.text %></p>
    </article>
  <% unless @post.comments.size == 0 %>
    <ul class="container">
      <% @post.comments.each do |comment| %>
        <li>
          <span><%= comment.author.name %>:</span>
          <span><%= comment.text %></span>
          <% if can? :delete, comment %>
            <%= button_to "Delete", user_post_comment_path(@post.author, @post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </li>
      <% end %>
  </ul>
  <% end %>
  <div class="d-flex">
    <%= link_to 'Comment', new_user_post_comment_path(@user, @post), class: 'btn btn-outline-primary' %>
    <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes" do |f| %>
      <%= f.submit 'Like', class: 'btn btn-outline-info mx-2' %>
    <% end %>
    <%= link_to 'Back to posts', user_posts_path, class: 'btn btn-outline-secondary' %>
  </div>
</article>

app/views/users/index.html.erb
<section class="main container">
  <h1>All Users</h1>
  <% @users.each do |user| %>
    <%= render 'shared/user', user: user %>
  <% end %>
</section>

app/views/users/show.html.erb
<article class = "main">

  <%= render 'shared/user', user: @user %>

  <article class="bio__container container">
    <h3>Bio</h3>
    <span><%= @user.bio %></span>
  </article>

  <article class="posts_container container">
    <% @user.recent_post.each_with_index do |post, idx| %>
      <article class="posts__container container">
        <h3>Post #<%= idx+1 %></h3>
        <p><%= post.text.truncate_words(15, omission: '...(continued)') %></p>
        <div class="comments__likes__count">
          <span><em><b>Comments:
            <%= post.comments_counter %></em></b></span>
          <span><em><b>Likes:
            <%= post.likes_counter %></em></b></span>
        </div>
        <%= link_to user_post_path(@user.id, post.id) do %>
          <button type="button" class="view-posts-btn my-1">View post</button>
        <% end %>
      </article>
    <% end %>
  </article>
  <div class="btn_container container d-flex  align-items-center">
    <%= link_to "See all posts", user_posts_path(@user.id), class: 'btn btn-outline-info my-3 ' %>
    <%= link_to "Add post", new_user_post_path(@user.id), class: 'btn btn-outline-primary mx-2' %>
  </div>
</article>